---
- name: Install Zabbix repo
  tags: zabbix_agent
  sudo: yes
  register: zabbix_agent_install_zabbix_repo
  template:
    src=apt.list.j2
    dest=/etc/apt/sources.list.d/zabbix.list
    owner=0
    group=0
    mode=0644

- name: Install Zabbix repo GPG key
  tags: zabbix_agent
  sudo: yes
  register: zabbix_agent_install_zabbix_repo_gpg_key
  apt_key:
    state=present
    url={{ zabbix_agent_repo_home }}/zabbix-official-repo.key

- name: Update apt cache
  tags: zabbix_agent
  sudo: yes
  when:
    - zabbix_agent_install_zabbix_repo.changed
    - zabbix_agent_install_zabbix_repo_gpg_key.changed
  apt:
    update_cache=yes
