---
- name: Assert supported platform
  tags: zabbix_client
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']

- name: Assert required vars
  tags: zabbix_client
  assert:
    that:
      - zabbix_customer_name not in (None, "")
      - zabbix_customer_hash not in (None, "")


- name: Include OS specific variables
  tags: zabbix_client
  include_vars: "{{ ansible_os_family }}.yml"


- include: RedHat.yml
  tags: zabbix_client
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  tags: zabbix_client
  when: ansible_os_family == 'Debian'


- name: Install Zabbix agent
  tags: zabbix_client
  with_items: zabbix_agent_package_list
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"


- name: Install required directories
  tags: zabbix_client
  with_items:
    - "{{ zabbix_log_directory }}"
    - "{{ zabbix_run_directory }}"
    - "{{ zabbix_conf_include_directory }}"
  file:
    state=directory
    dest={{ item }}
    owner={{ zabbix_user_name }}
    group={{ zabbix_user_group }}
    mode=0755


- name: Install Zabbix configuration
  tags: zabbix_client
  notify: service restart zabbix-agent
  template:
    src=zabbix_agentd.conf.j2
    dest={{ zabbix_conf_file }}
    owner=0
    group=0
    mode=644


- include: mysql.yml
  when: zabbix_install_mysql


- name: Ensure zabbix-agent is running
  tags: zabbix_client
  service:
    state=started
    name={{ zabbix_service }}
