---
- name: Assert supported platform
  tags: zabbix_agent
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']

- name: Assert required vars
  tags: zabbix_agent
  assert:
    that:
      - zabbix_agent_server_name not in (None, "")
      - zabbix_agent_server_ip not in (None, "")
      - zabbix_agent_customer_name not in (None, "")
      - zabbix_agent_customer_hash not in (None, "")


- name: Include OS specific vars
  tags: zabbix_agent
  include_vars: "{{ ansible_os_family }}.yml"


- include: RedHat.yml
  tags: zabbix_agent
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  tags: zabbix_agent
  when: ansible_os_family == 'Debian'


- name: Install Zabbix agent
  tags: zabbix_agent
  sudo: yes
  with_items: zabbix_agent_package_list
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"


- name: Install required directories
  tags: zabbix_agent
  sudo: yes
  with_items:
    - "{{ zabbix_agent_log_directory }}"
    - "{{ zabbix_agent_run_directory }}"
    - "{{ zabbix_agent_conf_directory }}"
  file:
    state=directory
    dest={{ item }}
    owner={{ zabbix_agent_user_name }}
    group={{ zabbix_agent_user_group }}
    mode=0755


- name: Install Zabbix configuration
  tags: zabbix_agent
  sudo: yes
  notify: service restart zabbix-agent
  template:
    src=zabbix_agentd.conf.j2
    dest={{ zabbix_agent_conf_file }}
    owner=0
    group=0
    mode=644


- include: mysql.yml
  tags: zabbix_agent
  when: zabbix_agent_mysql_enable


- name: Ensure zabbix-agent service
  tags: zabbix_agent
  sudo: yes
  service:
    state=started
    enabled=yes
    name={{ zabbix_agent_service }}
