---
- name: Install Zabbix repo in Redhat derivatives
  tags: zabbix_client
  when: ansible_os_family == 'RedHat'
  yum:
    state=present
    name=http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ centos_version }}/{{ centos_arch }}/{{ zabbix_reponame_centos }}

- name: Install the zabbix-agent package in Redhat derivatives
  tags: zabbix_client
  when: ansible_os_family == 'RedHat'
  with_items: zabbix_agent_pkgs
  yum:
    state=installed
    name={{ item }}

- name: Install Zabbix repo in Debian derivatives
  tags: zabbix_client
  when: ansible_os_family == 'Debian'
  with_items:
    - wget http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ debian_os_type }}/pool/main/z/zabbix-release/{{ zabbix_reponame_debian }}
    - dpkg -i {{ zabbix_reponame_debian }}
  command: "{{ item }}"

- name: Install the zabbix-agent package in Debian derivatives
  tags: zabbix_client
  when: ansible_os_family == 'Debian'
  with_items: zabbix_agent_pkgs
  apt:
    state=installed
    name={{ item }}
    update_cache=yes
    cache_valid_time=3600

- name: Install zabbix_agent.conf template
  tags: zabbix_client
  notify: service restart zabbix-agent
  template:
    src=zabbix_agentd.conf.j2
    dest=/etc/zabbix/zabbix_agentd.conf
    mode=644

- name: Create mysql config directory
  tags: zabbix_client
  file:
    dest=/var/lib/zabbix
    mode=755
    owner=root
    group=root
    state=directory

- name: Install mysql config
  tags: zabbix_client
  copy:
    src=.my.cnf
    dest=/var/lib/zabbix/.my.cnf
    owner=root
    group=root
    mode=644

- name: Ensure zabbix-agent is running
  tags: zabbix_client
  service:
    state=started
    name=zabbix-agent
