---
# TODO fix me
- name: Register rsyslog running
  tags: zabbix_agent
  register: zabbix_agent_rsyslog_running
  ignore_errors: true
  failed_when: false
  command: pgrep rsyslog

- name: Install rsyslog conf.d directory
  tags: zabbix_agent
  sudo: yes
  when:
    - zabbix_agent_rsyslog_running.rc == 0
    - zabbix_agent_syslog_configuration not in (None, "")
  file:
    state=directory
    dest=/etc/rsyslog.d
    owner=0
    group=0
    mode=0755

- name: Install rsyslog configuration for zabbix
  tags: zabbix_agent
  sudo: yes
  when:
    - zabbix_agent_rsyslog_running.rc == 0
    - zabbix_agent_syslog_configuration not in (None, "")
  notify: service restart rsyslog
  template:
    src=rsyslog_zabbix.conf.j2
    dest=/etc/rsyslog.d/zabbix.conf
    owner=0
    group=0
    mode=0644
#    validate='rsyslogd -N 1 -f %s'
# TODO rsyslog validation returns 0 on Ubuntu/Trusty all the time
