---
- name: service restart zabbix-agent
  tags: zabbix_agent
  sudo: yes
  when: zabbix_agent_allow_restart
  service:
    state=restarted
    name={{ zabbix_agent_service }}

- name: service restart rsyslog
  tags: zabbix_agent
  sudo: yes
  when: zabbix_agent_allow_restart_rsyslog
  service:
    state=restarted
    name=rsyslog

- name: service reload apache2
  tags: zabbix_agent
  sudo: yes
  service:
    state=reloaded
    name={{ zabbix_agent_apache2_service }} 
